### ISSUE TITLE
Allow creation of user with bridge-generated username

### ISSUE THREAD

**Issue by blargoner** [blargoner/jshue#12]
In the future, the Hue API will no longer support creating users with custom usernames on the bridge, only users with bridge-generated usernames. A new bridge method will need to be added to jsHue to support this change.

It will look something like:

```js
var bridge = jsHue().bridge('192.168.1.2');
bridge.createUser('foo application', function(data) {
    // extract bridge-generated username from returned data
    var user = bridge.user(data[0].success.username);
});
```

**Comment by Mysterarts** [comment]
Hi blargoner,
Thanks for your tool :)
Do you have a milestone for this enhancement?

**Comment by blargoner** [comment]
@Mysterarts v0.3.0. :)

**Comment by Mysterarts** [comment]
Thanks a lot!

**Comment by derjust** [comment]
Interessting - I just used 
```javascript
hue.bridge(bridgeIp).user().create("MyApp", function(successResultArray){});
```
and that worked with the new API. 
But thanks for the updated version.

**Comment by blargoner** [comment]
@derjust Nice workaround. With the new version, you can avoid instantiating a user() object twice.
