### ISSUE TITLE
Store the "user info" to use without authentication on every page reload?

### ISSUE THREAD

**Issue by warddem** [blargoner/jshue#15]
Hi,

I managed to get authenticated and switch the lights on/off (inside the bridge.createUser function).

How do I store the "user info" to use it again later (without authentication on every page reload)?

tried:
var user = 'AME8QQ.......';
user.setLightState(1, { on: false }, function(data) { /* ... */ });
error = user.setLightState is not a function

**Comment by blargoner** [comment]
You need to reinstantiate the user object, i.e.
```js
var user = jsHue().bridge('...').user('...');
user.setLightState(...);
```

**Comment by warddem** [comment]
Excellent, that did the trick.
thanks,
Ward
