### ISSUE TITLE
npm package please

### ISSUE THREAD

**Issue by nuclearspike** [blargoner/jshue#17]
Please have an npm wrapper for use with webpack/browserify. Npm packages are then managed for updates and devs can use the npm cdns out there. 😀

**Comment by nylki** [comment]
While we are at it, as a second step it could be useful to offer some more choice (minified version, es6 module), which would however require intervention from eg. `babel`, `uglify` and/or `rollup`.

**Comment by omahm** [comment]
There is a npm version, https://www.npmjs.com/package/jshue-module but it's version 0.3.0

**Comment by blargoner** [comment]
I published an [npm package](https://www.npmjs.com/package/jshue) with jsHue included "as is", as a vanilla JavaScript file. I'm not sure yet about repackaging the code in a different way (e.g. es6 module), but I welcome additional feedback about this.

**Comment by nylki** [comment]
@blargoner I made a PR with a small non invasive addition that makes jshue usable as a module: #19
Which I think is a good compromise by keeping it simple (without need of extra tooling) but still allowing bundlers to import jshue as a module.
