### ISSUE TITLE
Getting light state

### ISSUE THREAD

**Issue by eriksoderholm** [blargoner/jshue#9]
Thanks for this project, here's a (probably super-simple) question from a Javascript newbie ;-) I've got user.setLightState to work without issues so I can turn the lamp on or off, but how do I use getLight or getLights to check the status of the light? It just returns true (for sending the request) and not the actual status...

**Comment by blargoner** [comment]
Each API request is made asynchronously, so you need to pass callback functions which will be called with returned data.

```javascript
user.getLights(
    // callback with returned API data (which could be an API success or error)
    function(lights) { ... },
    // callback with error data (for XHR or JSON errors only)
    function(error) { ... }
);
```
Every method is like this, including setLightState, etc.
